version: '3.9'
services:
  megafall-viewer:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /Users/jihunjang/Downloads/ust/dataset:/datasets/ust/dataset:ro
      - /Users/jihunjang/Downloads/kisa-2:/datasets/kisa-2:ro
    environment:
      - PYTHONPATH=/app
